### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by ayrat555**
- change interface
- add tests
- add github actions

### CODE REVIEW

**Comment by ayrat555** [comment]
@jared-mackey one more pr for you. please take a look when you have time

**Comment by jared-mackey** [comment]
@ayrat555 This looks great. Can you resolve the conflicts? Once those are resolved I'll merge and push a new version. Thanks for your contribution!

**Comment by ayrat555** [comment]
@jared-mackey done

**Comment by jared-mackey** [comment]
@ayrat555 Thanks so much! These changes have been published to hex as 1.2.0

**Pull request merged**
